version: "3.7"
services:
  postgres-db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_DB: IILabTime
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 89
    ports:
      - "8089:89"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres-db:pgsql-server"
volumes:
  postgres-db-data:
  pgadmin-data: