name: Build IILabTimeBackend Jar

on:
  push:
    branches:
      - main
      - JIE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: |
          cd backend 
          mvn clean package -DskipTests
          rm -f target/*.jar.original

      - name: Move JAR to separate directory
        run: |
          mkdir -p artifact
          mv backend/target/*.jar artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IILabTimeBackend
          path: artifact/*